/**
 * Generates the two root-level SEO files into `public/` at build time:
 *
 *   • public/robots.txt   → crawl permissions + sitemap location
 *   • public/sitemap.xml  → every indexable URL, with lastmod/changefreq/priority
 *
 * Both are produced from `src/data/seo.js`, so a new page only has to be added
 * in one place. Run automatically by `npm run build`; can also be run alone
 * with `npm run seo`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { pages, SITE_URL } from '../src/data/seo.js';
import { ROUTES } from '../src/data/routes.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const publicDir = join(root, 'public');

const today = new Date().toISOString().slice(0, 10);

const priorityFor = (path) => pages[path]?.priority ?? 0.5;
const changefreqFor = (path) => pages[path]?.changefreq ?? 'monthly';

const urlEntries = Object.values(ROUTES)
  .filter((path) => pages[path])
  .map(
    (path) => `  <url>
    <loc>${SITE_URL}${path === '/' ? '/' : path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreqFor(path)}</changefreq>
    <priority>${priorityFor(path).toFixed(1)}</priority>
  </url>`,
  )
  .join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  VM Music Factory — XML sitemap
  Generated by scripts/generate-seo.mjs. Edit src/data/seo.js (not this file).
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${urlEntries}
</urlset>
`;

const robots = `# VM Music Factory — robots.txt
# Generated by scripts/generate-seo.mjs. Edit src/data/seo.js (not this file).

User-agent: *
Allow: /

# Nothing on this site is secret — everything public is indexable.
# Only the error page is kept out of the index (it also sends noindex, follow).
Disallow: /404.html

# Belt-and-braces: if a host is mis-configured and publishes the repository
# root instead of dist/, keep the source folders out of search results.
Disallow: /src/
Disallow: /scripts/
Disallow: /dist/
Disallow: /node_modules/

# Crawl-friendly: no crawl-delay, so Googlebot can fetch the whole site quickly.
Sitemap: ${SITE_URL}/sitemap.xml
Host: ${SITE_URL}
`;

await mkdir(publicDir, { recursive: true });
await writeFile(join(publicDir, 'sitemap.xml'), sitemap, 'utf8');
await writeFile(join(publicDir, 'robots.txt'), robots, 'utf8');

console.log(`[seo] robots.txt + sitemap.xml written for ${Object.keys(pages).length} URLs`);
