/**
 * ---------------------------------------------------------------------------
 * PRERENDER — the "best of both worlds" step
 * ---------------------------------------------------------------------------
 * The site is a client-side-rendered React app. This script additionally
 * renders each route to static HTML at build time, then:
 *
 *   • injects the per-route <title>, meta description, canonical, robots and
 *     Open Graph tags (from src/data/seo.js),
 *   • writes `dist/<route>/index.html` and `dist/<route>.html` so the clean URL
 *     works on Vercel (cleanUrls) as well as on any plain static host,
 *   • writes a noindex `dist/404.html`.
 *
 * The SSR bundle it imports is built into `node_modules/.cache/vmmf-ssr`, so
 * `dist/` contains nothing but the public site.
 *
 * Result: real HTML on the first byte for users and crawlers, while the client
 * React app hydrates on top and takes over navigation.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { pages, absoluteUrl } from '../src/data/seo.js';
import { ROUTES } from '../src/data/routes.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'dist');
const serverEntry = join(root, 'node_modules', '.cache', 'vmmf-ssr', 'entry-server.js');

const escapeAttr = (value = '') =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** Per-route head tags, replacing everything between the seo markers. */
function headTags({ title, description, canonical, image, noindex = false }) {
  const robots = noindex
    ? 'noindex, follow'
    : 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1';

  return [
    `<title>${escapeAttr(title)}</title>`,
    `<meta name="description" content="${escapeAttr(description)}" />`,
    `<link rel="canonical" href="${canonical}" />`,
    `<meta name="robots" content="${robots}" />`,
    '<meta name="author" content="VM Music Factory" />',
    '<meta name="theme-color" content="#0b0b0f" />',
    `<meta property="og:type" content="${canonical.endsWith('/') ? 'website' : 'article'}" />`,
    '<meta property="og:site_name" content="VM Music Factory" />',
    '<meta property="og:locale" content="en_IN" />',
    `<meta property="og:title" content="${escapeAttr(title)}" />`,
    `<meta property="og:description" content="${escapeAttr(description)}" />`,
    `<meta property="og:url" content="${canonical}" />`,
    `<meta property="og:image" content="${image}" />`,
    '<meta property="og:image:width" content="1200" />',
    '<meta property="og:image:height" content="630" />',
    '<meta property="og:image:alt" content="VM Music Factory — recording studio in Bengaluru, Karnataka" />',
    '<meta name="twitter:card" content="summary_large_image" />',
    `<meta name="twitter:title" content="${escapeAttr(title)}" />`,
    `<meta name="twitter:description" content="${escapeAttr(description)}" />`,
    `<meta name="twitter:image" content="${image}" />`,
  ].join('\n    ');
}

function withHead(template, tags) {
  const start = template.indexOf('<!-- seo:start');
  const end = template.indexOf('<!-- seo:end -->');
  if (start === -1 || end === -1) {
    throw new Error('index.html is missing the <!-- seo:start --> / <!-- seo:end --> markers');
  }
  return (
    template.slice(0, start) +
    '<!-- seo:start — generated by scripts/prerender.mjs -->\n    ' +
    tags +
    '\n    ' +
    template.slice(end)
  );
}

async function writeRoute(path, html) {
  const targets = [];

  if (path === '/') {
    targets.push(join(dist, 'index.html'));
  } else {
    const clean = path.replace(/^\//, '');
    targets.push(join(dist, clean, 'index.html'));
    targets.push(join(dist, `${clean}.html`));
  }

  for (const target of targets) {
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, html, 'utf8');
  }

  return targets.length;
}

const template = await readFile(join(dist, 'index.html'), 'utf8');
const { render } = await import(pathToFileURL(serverEntry).href);

let files = 0;

for (const [path, meta] of Object.entries(pages)) {
  const appHtml = render(path);
  const html = withHead(
    template.replace('<!--app-html-->', appHtml),
    headTags({
      title: meta.title,
      description: meta.description,
      canonical: absoluteUrl(path),
      image: meta.ogImage,
    }),
  );
  files += await writeRoute(path, html);
  console.log(`[prerender] ${path} → ${appHtml.length.toLocaleString()} chars of HTML`);
}

// 404 — noindex, and never listed in the sitemap.
const notFoundHtml = withHead(
  template.replace('<!--app-html-->', render('/this-page-does-not-exist')),
  headTags({
    title: 'Page not found | VM Music Factory',
    description:
      'The page you were looking for does not exist. Browse the VM Music Factory website or call the studio on +91 95133 45544.',
    canonical: absoluteUrl(ROUTES.home),
    image: `${absoluteUrl(ROUTES.home).replace(/\/$/, '')}/og-image.png`,
    noindex: true,
  }),
);
await writeFile(join(dist, '404.html'), notFoundHtml, 'utf8');
files += 1;

// Vercel/Netlify can fall back to index.html for unknown client-side routes.
console.log(`[prerender] done — ${files} HTML files written to dist/`);
